
Neos:
  Neos:
    modules:
      administration:
        submodules:
          fusion-browser:
            label: 'Fusion Browser'
            controller: \Flowpack\Fusion\Browser\Controller\FusionController
            description: ''
            icon: icon-list
            privilegeTarget: 'Flowpack.Fusion.Browser:AllActions'
